sylius_grid:
    grids:
        odiseo_banner_banner:
            driver:
                name: doctrine/orm
                options:
                    class: "%odiseo_banner.model.banner.class%"
            sorting:
                createdAt: desc
            fields:
                code:
                    type: string
                    label: sylius.ui.code
                    sortable: ~
                image:
                    type: twig
                    label: sylius.ui.image
                    path: imageName
                    options:
                        template: "@OdiseoSyliusBannerPlugin/admin/banner/grid/field/image.html.twig"
                mobileImage:
                    type: twig
                    label: odiseo_banner.ui.mobile_image
                    path: mobileImageName
                    options:
                        template: "@OdiseoSyliusBannerPlugin/admin/banner/grid/field/mobile_image.html.twig"
                enabled:
                    type: twig
                    label: sylius.ui.enabled
                    sortable: ~
                    options:
                        template: "@SyliusUi/grid/field/enabled.html.twig"
                createdAt:
                    type: datetime
                    label: sylius.ui.creation_date
                    sortable: ~
                    options:
                        format: d-m-Y H:i
            filters:
                code:
                    type: string
                    label: sylius.ui.code
                enabled:
                    type: boolean
                    label: sylius.ui.enabled
                createdAt:
                    type: date
                    label: sylius.ui.creation_date
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
