imports:
    - { resource: "@OdiseoSyliusBannerPlugin/config/app/twig_hooks/**/*.yaml" }
    - { resource: "@OdiseoSyliusBannerPlugin/config/app/grids/**/*.yaml" }
    - { resource: "@OdiseoSyliusBannerPlugin/config/app/resources/**/*.yaml" }
    - { resource: "@OdiseoSyliusBannerPlugin/config/app/fixtures/*.yaml"}

knp_gaufrette:
    stream_wrapper: ~
    adapters:
        odiseo_banner_image:
            local:
                directory: "%sylius_core.public_dir%/media/banner-image"
                create: true
    filesystems:
        odiseo_banner_image:
            adapter: odiseo_banner_image

liip_imagine:
    loaders:
        odiseo_banner_image:
            filesystem:
                data_root: "%sylius_core.public_dir%/media/banner-image"
    filter_sets:
        odiseo_banner_image:
            data_loader: odiseo_banner_image
            filters:
                thumbnail: { size: [1920, 600], mode: inset }
        odiseo_banner_mobile_image:
            data_loader: odiseo_banner_image
            filters:
                thumbnail: { size: [768, 1000], mode: inset }
