imports:
    - { resource: "@OdiseoSyliusBannerPlugin/config/app/twig_hooks/**/*.yaml" }
    - { resource: "@OdiseoSyliusBannerPlugin/config/app/grids/**/*.yaml" }
    - { resource: "@OdiseoSyliusBannerPlugin/config/app/resources/**/*.yaml" }
    - { resource: "@OdiseoSyliusBannerPlugin/config/app/fixtures/*.yaml"}

knp_gaufrette:
    stream_wrapper: ~
    adapters:
        odiseo_banner_image:
            local:
                directory: "%sylius_core.public_dir%/media/banner-image"
                create: true
    filesystems:
        odiseo_banner_image:
            adapter: odiseo_banner_image
