Odiseo\SyliusBannerPlugin\Entity\BannerTranslation:
    properties:
        imageFile:
            - NotBlank:
                message: 'odiseo_banner.banner_translation.image_file.not_blank'
                groups: ['odiseo_image_create']
