odiseo_sylius_banner_admin_banner:
    resource: |
        alias: odiseo_sylius_banner.banner
        section: admin
        templates: "@SyliusAdmin/Crud"
        except: ['show']
        redirect: index
        grid: odiseo_sylius_banner_banner
        permission: true
        vars:
            all:
                templates:
                    form: '@OdiseoSyliusBannerPlugin/admin/banner/_form.html.twig'
            index:
                icon: image
    type: sylius.resource
